# Docker Compose のバージョンを指定します
version: "3.9"
# 実行するコンテナを記述していく
services:
  # Laravelコンテナ
  app:
    # Dockerfile のあるディレクトリのパスを指定
    build: ./infra/php
    # ./backend ディレクトリをappサービスのコンテナ内 /work へマウント
    volumes:
      - ./backend:/work

  # Webサーバーコンテナ
  web:
    # コンテナを起動させるイメージを指定します
    image: nginx:1.20-alpine
    # nginxへ外(ホスト側)からコンテナ内へアクセスさせるため公開用のポート
    ports:
      - 8080:80
    # ホスト側にあるディレクトリ、ファイルをコンテナ内へマウント
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  # DBコンテナ
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: